# -*- coding: utf-8 -*-
"""ST code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQTnITHX5lLrzbR2-DItijIKw6Z3MprZ
"""

#!pip install streamlit
import streamlit as st
import pickle
import os

st.title("🩺 Disease Prediction System")

if not os.path.exists("disease_model.pkl"):
    st.error("Model file not found!")
    st.stop()

if not os.path.exists("label_encoder.pkl"):
    st.error("Encoder file not found!")
    st.stop()

model = pickle.load(open("disease_model.pkl", "rb"))
le = pickle.load(open("label_encoder.pkl", "rb"))


# model UI


import streamlit as st
import pickle
import numpy as np

# Page config
st.set_page_config(
    page_title="Disease Prediction System",
    page_icon="🩺",
    layout="centered"
)

# Load model & encoder
model = pickle.load(open("disease_model.pkl", "rb"))
le = pickle.load(open("label_encoder.pkl", "rb"))

# ---------- TITLE ----------
st.markdown(
    "<h1 style='text-align: center; color: #2E86C1;'>🩺 Disease Prediction System</h1>",
    unsafe_allow_html=True
)

st.markdown(
    "<p style='text-align: center;'>Predict disease based on selected symptoms</p>",
    unsafe_allow_html=True
)

st.divider()

# ---------- SIDEBAR ----------
st.sidebar.header("🧾 Select Symptoms")

symptom_list = [
    "Fever", "Cough", "Headache", "Fatigue", "Sore Throat",
    "Runny Nose", "Body Pain", "Nausea",  "Diarrhea"
]

selected_symptoms = st.sidebar.multiselect(
    "Choose symptoms:",
    symptom_list
)

# ---------- MAIN LOGIC ----------
input_data = [1 if symptom in selected_symptoms else 0 for symptom in symptom_list]
input_array = np.array(input_data).reshape(1, -1)

st.divider()

# ---------- PREDICTION ----------
if st.button("🔍 Predict Disease"):
    if len(selected_symptoms) == 0:
        st.warning("⚠️ Please select at least one symptom")
    else:
        prediction = model.predict(input_array)
        disease = le.inverse_transform(prediction)[0]

        st.success("✅ Prediction Successful!")

        st.markdown(
            f"""
            <div style="
                background-color:#E8F6F3;
                padding:20px;
                border-radius:10px;
                text-align:center;
                font-size:22px;
                color:#117864;">
                <b>Predicted Disease:</b><br>{disease}
            </div>
            """,
            unsafe_allow_html=True
        )

# ---------- FOOTER ----------
st.markdown("<br><hr>", unsafe_allow_html=True)
st.markdown(
    "<p style='text-align:center; font-size:14px;'>Made using Machine Learning & Streamlit</p>",
    unsafe_allow_html=True
)